version: "3"
services:
  app:
    image: node:18-alpine
    restart: always
    working_dir: /app
    command: sh -c "npm i -g pnpm && pnpm install && node src/server.js"
    ports:
      - 3000:3000
    volumes:
      - .:/app