version: "3"
services:
  app:
    image: statewitness
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /opt/statewitness/src:/app/src
      - /opt/statewitness/data:/app/data